spring:
  config:
    import:
      - 'classpath:/yml/application-oauth.yml'
      - 'classpath:/yml/application-logging.yml'
  application:
    name: chat
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:mariadb://localhost:3306/chat
    url: jdbc:log4jdbc:mariadb://192.168.0.243:3306/chat
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect # MariaDB Dialect 명시적 설정
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      resolve-lazily: true

server:
  port: 8087
  error:
    path: /error
    include-exception: true
    include-stacktrace: always
    whitelabel:
      enabled: false
  tomcat:
    max-http-post-size: 20971520
    max-swallow-size: 20971520

file:
  upload:
    path: ./uploads

# JWT 설정
jwt:
  secret: 'a-very-long-and-secure-secret-key-that-is-at-least-256-bits-long-for-hs256' # TODO: 실제 운영에서는 외부 환경변수로 관리해야 함
  expiration_ms: 86400000 # 24시간 (1일)
